1005
Altu-Bitu/Altu-Bitu_Hayun pull request #11
Opened 2021-10-10 06:06 UTC by haayun

2021-10-10 06:08 UTC, haayun commented
17281번에서 시간초과가 나는데 어떤 부분을 수정하면 좋을지 조언해주시면 감사하겠습니다..!

2021-10-10 10:14 UTC, bsa0322 requested changes
p2. 17281은 조금만 수정하면 바로 맞았습니다 나오겠네요!!!! 수정 후, 저 리뷰어로 호출해주세요~! 다른 부분들도 수정해보셔도 좋아요! 민겸수 문제도 코멘트 남겼습니다! 수고하셨습니다!!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1074.cpp
> +	}
오...재귀를 한 번만 호출해서 사분면 중 어디에 해당하는지 위치를 찾아가는 분할 정복은 생각 못해봤는데 좋네요!! 👍
샘플코드는 4등분으로 나눈 후, 반대로 위치에 해당하지 않는 부분만큼의 칸을 합치는 방식의 풀이니 나중에 확인해보셔도 좋을 것 같아요!!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1244.cpp
> +		light[i] = 1 - light[i];
p3. 상태는 0 혹은 1 밖에 없네요! 조금 더 직관적으로 반대 상태로 만들어주도록 구현할 수 있을 것 같아요! 자료형도 더 어울리는 자료형이 있겠네요!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1244.cpp
> +	}
👍👍👍

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +	} while (next_permutation(test.begin(), test.end()));	//2번부터 9번까지 순열 생성
test는 1번 인덱스부터 시작하는데, next_permutation은 몇 번 인덱스부터 시작해서 순열을 생성하나요? 문제에서 원하는 모든 경우의 수보다 불필요한 경우가 계산되고 있어요! 그래서 시간초과가 납니다!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17829.cpp
> +	}
p2. 정렬을 직접 구현해주셨네요! 지금도 좋지만, 정렬하기 더 편한 방법이 있죠!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17829.cpp
> +//의도대로 푼 건지 모르겠다? 시간이 오래 걸리는 것 같다.
시간 오래 걸리는 편 아니에요!! 오히려 빨리 걸리는 편이십니다! 의도대로 잘 풀어주셨어요 ! 👍
다만, 지금은 2 * 2에서 2번째 큰 수를 계속 리턴받아서 size/2 * size/2만큼의 행렬을 계속 만들고, 매개변수로 보내주면서 메모리가 조금 많이 들고 있어요! size가 1이 될 때까지 분할을 계속한 후에, 2번째로 큰 수를 계속 받아서 크기가 2 * 2인 행렬을 계속 유지해주면 지금보다 시간은 조금 더 걸리지만 메모리를 줄일 수 있어요! 나중에 샘플코드 확인해보셔도 좋을 것 같습니다~~!!

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1802.cpp
> +	return foldable(l) && foldable(r);
p2. 여기까지 왔다는 건 현재의 종이가 양 옆 문자가 서로 반대인 걸 만족하는 경우일 거예요!! 그렇다면 여기서 왼쪽 부분이 또 좌우 반대를 만족한다면, 오른쪽 부분은 어떻게 될까요?

2021-10-10 10:14 UTC, bsa0322 commented on 10월 5일 - 분할 정복/21314.cpp
> +//어디서 틀린지 모르겠다..???
만약 MKMMM 이란 민겸수가 있다 해볼께요! 이 경우의 최댓값은 지금대로라면 50100이 나올텐데, 과연 이게 최댓값이 맞을까요? 마지막으로 끝나는 MMM을 주목해주세요!

2021-10-10 20:08 UTC, haayun commented
리뷰 감사합니다~👍 1244는 bool 배열로 변경했는데 적절할까요? 21314는 아예 다시 풀었습니다..

2021-10-11 06:03 UTC, bsa0322 approved these changes
p2. 수정해주신 부분들 다 확인했습니다! 아주 좋아요! 👍 머지하셔도 괜찮습니다!! 혹시 또 수정하시면 저 다시 호출해주세요. 수고하셨습니다~!!!

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1244.cpp
> +bool light[101];
넵! bool 자료형 사용 좋아요!!! 👍

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +	} while (next_permutation(test.begin() + 1, test.end()));	//2번부터 9번까지 순열 생성 -> *begin()+1으로 2번부터 순열 생성하도록
👍👍👍

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17829.cpp
> +	return arr[1];
👍👍👍

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/21314.cpp
> +			last_k = i;	//K 인덱스 업데이트
p2. 지금은 시간복잡도가 O(n^2)이네요! O(n) 만에 풀 수 있어요! 지금은 K가 나오면, 문자를 만들어주는데 K가 나오기 이전에도 계속 문자를 만들어오면 어떨까요? 여유가 되신다면 수정해보셔도 좋고, 아니면 샘플코드 확인해보셔도 좋아요~!!!

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/21314.cpp
> +		max_mk.push_back('1');
👍👍👍

2021-10-11 06:03 UTC, bsa0322 commented on 10월 5일 - 분할 정복/21314.cpp
> +			last_k = i;		//K 인덱스 업데이트
마찬가지로 O(n) 으로 풀 수 있어요!

2021-10-11 07:51 UTC, bsa0322 reviewed
좋아요!! 수고하셨습니다! 머지해주세요!

2021-10-11 08:17 UTC, merged