0921
Altu-Bitu/Altu-Bitu_Hayun pull request #6
Opened 2021-09-25 14:49 UTC by haayun

2021-09-26 07:58 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다~
지금 그럼 성공한 문제가 5문제인걸까요?
좀 더 힌트를 드리고 싶었는데, 주석이 적다보니 제가 코드를 이해하기가 좀 어려워서 제대로 힌트를 드린지 모르겠어요! 이후로는 문제마다 주석을 적어주시면 좋겠습니다!
추가로 리팩토링할 부분이 꽤 있는데요~ 제가 코멘트 드린 부분은 가능하면 다 수정해주세요!
수정 후 리뷰어로 저 호출해주세요~

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/10448.cpp
> +	}
굳이 getT 함수를 만들지 않고 이 작업에서 배열에 삼각수를 넣어도 좋아요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +	}
어차피 버튼은 겨우 10개니까 배열에 그대로 넣어서 하나하나 find 함수를 사용하는 것보단 한번에 접근하는 방법이 좋아요. 그럼 어떻게 구현하면 될까요?

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +		}
*이 로직이 맞을까요? 갈 수 있는 채널도 갈 수 없다고 나오게 될 수 있어보여요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +	}
이건 같은 논리로 엮이는 연산이라 이렇게 분리되는 건 좋지 않아요
물론 그대로 이어 붙이면 안되겠지만, 함수랑 같이 리팩토링 해볼까요?
그리고 주석이 있으면 좋을 것 같아요! 논리를 이해하는데 시간이 걸리네요~ 제가 오해할 수도 있구요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +
혹시 vs를 쓰시나요? 한글이 깨지지 않는 옵션이 있었던 것 같기도 해요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +
p1
max는 함수가 있기 때문에 전역변수명으로 쓰면 컴파일이 안돼요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +		max = sum > max ? sum : max;
여길 꼭 삼항연산자로 해야할까요?

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +	down = 2 * n - 1;
down 변수가 내리는 위치를 의미하는 걸까요?
그렇다면 이게 왜 2*n-1인지 이해가 안돼요...!

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +		down = down - 1 > 0 ? down - 1 : 2 * n - 1;
이 조건에 의하면  up down이 1이었다면 그 다음엔 2n-1이 되겠네요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +			if (robot[i] == true && robot[(i + 1) % (2 * n - 1)] == false && belt[(i + 1) % (2 * n)] > 0) {
두번째 조건과 세번째 조건이 다른 위치를 나타내는 것 같은데 어떤 의미일까요?

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +int main() {
단계들은 함수로 다 분리하는게 좋아요~

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +	}
입력을 받으면서 처리할 수 있고, 중복되기도 하는 연산들이 몇몇 보이네요~ 리팩토링 할 수 있어요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +	cout << fourth(v) << "\n";
함수로 분리하신건 좋지만 함수 이름은 각 함수가 하는 일을 나타내는게 좋아요!
지금 이 이름만 봐서는 어떤 함수인지 알 수 없으니까요

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +		}
p2
인덴테이션이 너무 깊게 들어가네요! 그리고 k는 그냥 처음부터 string으로 받아도 괜찮아요
기왕 total을 init으로 초기화했으니, line 27~28 사이에 이번 i가 탐색할 가치가 있는지 확인하는 코드를 넣을 수 있지 않을까요?

2021-09-26 07:58 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/3077.cpp
> +	}
p2
저희 이것보다 훨씬 간단한 방법을 배우지 않았었나요?

2021-09-27 08:10 UTC, haayun commented
14501, 20055는 다시 봐도 여전히 푸는 방법을 잘 모르겠어서 업데이트를 하지 못했습니다.. 다음 과제부터는 주석을 자세히 달아보겠습니다. 감사합니다!

2021-09-27 09:41 UTC, HyunJiLim0406 approved these changes
p2
수고하셨습니다~ 샘플 코드 올라오면 20055번만 주석달아서 업로드 해주세요!
그리고 지금 좀 더 리팩토링할 부분들이 있어서 거기만 조금 더 수정할까요?
수정하시고 리뷰어로 저 호출해주세요! 주석까지 달고 난 뒤에 호출하셔도 괜찮아요~

2021-09-27 09:41 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/10448.cpp
> +vector<bool> check() {
p2
지금 이 함수가 삼각수를 찾는 연산과 삼각수를 3개 더한 값을 찾는 연산 총 2개를 하고 있어요!
분리해주세요~

2021-09-27 09:41 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +			return false;
여기 if 문은 그냥 `if(!button[a%10])`으로 하는게 더 좋아요!

2021-09-27 09:41 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +	return 0;
대부분의 연산을 입력을 받으며 처리할 수 있게 됐지만...! 그래도 각 연산을 함수로 분리해주세요!

2021-09-27 09:41 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +		cin >> k >> s >> b;
가능하면 입력은 메인에서 받아주세요!
지금 이상태는 메인을 그대로 함수로 옮긴것과 다르지 않아서 잘 만든 함수라고 보기는 어려워요!

2021-09-28 04:44 UTC, HyunJiLim0406 reviewed
p3
확인했습니다~ 근데 20055번은 주석을 더 달아주셔야 해요
수정 후 다시 호출해주세요!

2021-09-28 04:44 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +int main() {
주석은 괄호를 제외한 모든 라인에 달아주셔야 합니다!

2021-09-28 05:22 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 머지해주세요~

2021-09-28 05:25 UTC, merged